ALTER TABLE users ADD COLUMN social_id VARCHAR(255) UNIQUE;
ALTER TABLE users ADD COLUMN social_type VARCHAR(50);
ALTER TABLE users CHANGE COLUMN email email VARCHAR(100) NULL;
ALTER TABLE users CHANGE COLUMN username username VARCHAR(50) NOT NULL;
